%% run_oxsa_amares.m
%  Pre-configured OXSA AMARES fitting script
%  Generated by MRS Basis Set Converter on 2026-05-24T21:12:44
%  Source basis set: gava_priors.txt
%  TE = 26.0 ms  |  SF = 123.2600 MHz  |  SW = 4000.0 Hz
%  Carrier PPM = 4.6500
%
%  INSTRUCTIONS:
%    1. Set oxsaRoot to your OXSA installation folder
%    2. Set subjectFile to your MRS data file (.mat MARSS format)
%    3. Set outputDir for results
%    4. Run this script in MATLAB
%
%  Reference: Purvis et al., PLOS ONE 2017, doi:10.1371/journal.pone.0185356

clear; clc; close all;

%%%%%%%% USER SETTINGS %%%%
oxsaRoot    = '/path/to/OXSA';           % <-- SET THIS
subjectFile = '/path/to/your/data.mat';  % <-- SET THIS (MARSS .mat format), however, can be any format
outputDir   = './oxsa_results/';         % <-- SET THIS
showPlot    = true;

%%%% SPECTRAL PARAMETERS (from basis set) %%%%
sf         = 123.260000;    % Larmor frequency (MHz)
sw         = 4000.0;     % Spectral width (Hz)
carrierPpm = 4.6500;  % Water reference (ppm)
seqte      = 26.0;     % Echo time (ms)

%%%% FITTING OPTIONS %%%%
options.apodization = 1;
options.lineshape   = 'L';
options.TolFun      = 1e-12;
options.TolX        = 1e-12;
options.MaxIter     = 2000;
options.MaxFunEvals = 1e6;

%%%% OXSA STARTUP %%%%
if exist(fullfile(oxsaRoot, 'startup.m'), 'file')
    run(fullfile(oxsaRoot, 'startup.m'));
    rehash toolboxcache;
else
    error('Could not find OXSA startup.m at: %s', oxsaRoot);
end

%%%% LOAD SUBJECT DATA %%%%
S = load(subjectFile);
if ~isfield(S, 'exptDat')
    error('Subject MAT file must contain exptDat struct (MARSS format)');
end
exptDat = S.exptDat;

fid  = double(exptDat.fid(:));
npts = double(exptDat.nspecC);
fid  = fid(1:npts);

% Scale and phase correct
scaleFactor = max(abs(fid));
fid = fid / scaleFactor;
fid = fid .* exp(-1j * angle(fid(1)));

dt       = 1 / sw;
timeAxis = ((0:npts-1)' * dt) + dt;
freqHz   = ((0:npts-1)' - npts/2) * (sw / npts);
ppmAxis  = carrierPpm + freqHz / sf;
specReal = real(fftshift(fft(fid)));

exptParams.samples          = npts;
exptParams.imagingFrequency = sf;
exptParams.dwellTime        = dt;
exptParams.beginTime        = dt;
exptParams.timeAxis         = timeAxis;
exptParams.ppmAxis          = freqHz / sf;

fprintf('Loaded: SF=%.4f MHz  SW=%.1f Hz  N=%d\n', sf, sw, npts);

if showPlot
    figure('Color','w','Name','Subject spectrum');
    plot(ppmAxis, specReal, 'k', 'LineWidth', 1);
    set(gca,'XDir','reverse'); xlim([0.5 4.5]);
    xlabel('ppm'); ylabel('Real'); title('Subject spectrum');
end

%%%% BUILD COMPONENTS %%%%
%  Pre-configured from basis set: 23 metabolites
%  Dominant PPM, linewidth bounds, and relative scales are set automatically.

components = struct( ...
    'metab', {}, 'componentName', {}, 'ppmExpected', {}, ...
    'ppmInit', {}, 'chemShiftHz', {}, 'chemShiftBoundsHz', {}, ...
    'linewidthInitHz', {}, 'linewidthBoundsHz', {}, ...
    'amplitudeInit', {}, 'amplitudeBounds', {}, ...
    'phaseInitDeg', {}, 'phaseBoundsDeg', {} );


    %% Tau
    c = struct();
    c.metab              = 'Tau';
    c.componentName      = 'Tau';
    c.ppmExpected        = 3.421000;
    c.ppmInit            = 3.421000;
    c.chemShiftHz        = -151.4865;
    c.chemShiftBoundsHz  = [-163.8125, -139.1605];
    c.linewidthInitHz    = 8;
    c.linewidthBoundsHz  = [1, 60];
    c.amplitudeInit      = 0.1000;
    c.amplitudeBounds    = [0, 0.5000];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

    %% Cr391
    c = struct();
    c.metab              = 'Cr391';
    c.componentName      = 'Cr391';
    c.ppmExpected        = 3.913000;
    c.ppmInit            = 3.913000;
    c.chemShiftHz        = -90.8426;
    c.chemShiftBoundsHz  = [-98.2382, -83.4470];
    c.linewidthInitHz    = 6;
    c.linewidthBoundsHz  = [1, 40];
    c.amplitudeInit      = 0.4000;
    c.amplitudeBounds    = [0, 2.0000];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

    %% Gln
    c = struct();
    c.metab              = 'Gln';
    c.componentName      = 'Gln';
    c.ppmExpected        = 3.753000;
    c.ppmInit            = 3.753000;
    c.chemShiftHz        = -110.5642;
    c.chemShiftBoundsHz  = [-125.3554, -95.7730];
    c.linewidthInitHz    = 8;
    c.linewidthBoundsHz  = [1, 60];
    c.amplitudeInit      = 0.1800;
    c.amplitudeBounds    = [0, 0.9000];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

    %% Gly
    c = struct();
    c.metab              = 'Gly';
    c.componentName      = 'Gly';
    c.ppmExpected        = 3.548000;
    c.ppmInit            = 3.548000;
    c.chemShiftHz        = -135.8325;
    c.chemShiftBoundsHz  = [-143.2281, -128.4369];
    c.linewidthInitHz    = 6;
    c.linewidthBoundsHz  = [1, 40];
    c.amplitudeInit      = 0.0600;
    c.amplitudeBounds    = [0, 0.3000];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

    %% Lac
    c = struct();
    c.metab              = 'Lac';
    c.componentName      = 'Lac';
    c.ppmExpected        = 4.097000;
    c.ppmInit            = 4.097000;
    c.chemShiftHz        = -68.1628;
    c.chemShiftBoundsHz  = [-78.0236, -58.3020];
    c.linewidthInitHz    = 7;
    c.linewidthBoundsHz  = [1, 40];
    c.amplitudeInit      = 0.0500;
    c.amplitudeBounds    = [0, 0.2500];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

    %% NAA
    c = struct();
    c.metab              = 'NAA';
    c.componentName      = 'NAA';
    c.ppmExpected        = 2.008000;
    c.ppmInit            = 2.008000;
    c.chemShiftHz        = -325.6529;
    c.chemShiftBoundsHz  = [-333.0485, -318.2573];
    c.linewidthInitHz    = 6;
    c.linewidthBoundsHz  = [1, 40];
    c.amplitudeInit      = 1.0000;
    c.amplitudeBounds    = [0, 5.0000];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

    %% GPC
    c = struct();
    c.metab              = 'GPC';
    c.componentName      = 'GPC';
    c.ppmExpected        = 3.212000;
    c.ppmInit            = 3.212000;
    c.chemShiftHz        = -177.2479;
    c.chemShiftBoundsHz  = [-184.6435, -169.8523];
    c.linewidthInitHz    = 6;
    c.linewidthBoundsHz  = [1, 40];
    c.amplitudeInit      = 0.1000;
    c.amplitudeBounds    = [0, 0.5000];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

    %% PCr393
    c = struct();
    c.metab              = 'PCr393';
    c.componentName      = 'PCr393';
    c.ppmExpected        = 3.930000;
    c.ppmInit            = 3.930000;
    c.chemShiftHz        = -88.7472;
    c.chemShiftBoundsHz  = [-96.1428, -81.3516];
    c.linewidthInitHz    = 6;
    c.linewidthBoundsHz  = [1, 40];
    c.amplitudeInit      = 0.2000;
    c.amplitudeBounds    = [0, 1.0000];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

    %% MM09
    c = struct();
    c.metab              = 'MM09';
    c.componentName      = 'MM09';
    c.ppmExpected        = 0.916000;
    c.ppmInit            = 0.916000;
    c.chemShiftHz        = -460.2528;
    c.chemShiftBoundsHz  = [-491.0678, -429.4378];
    c.linewidthInitHz    = 30;
    c.linewidthBoundsHz  = [5, 150];
    c.amplitudeInit      = 0.1500;
    c.amplitudeBounds    = [0, 0.7500];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

    %% GSH
    c = struct();
    c.metab              = 'GSH';
    c.componentName      = 'GSH';
    c.ppmExpected        = 3.769000;
    c.ppmInit            = 3.769000;
    c.chemShiftHz        = -108.5921;
    c.chemShiftBoundsHz  = [-123.3833, -93.8009];
    c.linewidthInitHz    = 8;
    c.linewidthBoundsHz  = [1, 60];
    c.amplitudeInit      = 0.0800;
    c.amplitudeBounds    = [0, 0.4000];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

    %% Asc
    c = struct();
    c.metab              = 'Asc';
    c.componentName      = 'Asc';
    c.ppmExpected        = 4.492000;
    c.ppmInit            = 4.492000;
    c.chemShiftHz        = -19.4751;
    c.chemShiftBoundsHz  = [-31.8011, -7.1491];
    c.linewidthInitHz    = 8;
    c.linewidthBoundsHz  = [1, 60];
    c.amplitudeInit      = 0.0600;
    c.amplitudeBounds    = [0, 0.3000];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

    %% GABA
    c = struct();
    c.metab              = 'GABA';
    c.componentName      = 'GABA';
    c.ppmExpected        = 2.284000;
    c.ppmInit            = 2.284000;
    c.chemShiftHz        = -291.6332;
    c.chemShiftBoundsHz  = [-306.4244, -276.8420];
    c.linewidthInitHz    = 8;
    c.linewidthBoundsHz  = [1, 60];
    c.amplitudeInit      = 0.1000;
    c.amplitudeBounds    = [0, 0.5000];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

    %% mI
    c = struct();
    c.metab              = 'mI';
    c.componentName      = 'mI';
    c.ppmExpected        = 3.522000;
    c.ppmInit            = 3.522000;
    c.chemShiftHz        = -139.0373;
    c.chemShiftBoundsHz  = [-151.3633, -126.7113];
    c.linewidthInitHz    = 8;
    c.linewidthBoundsHz  = [1, 60];
    c.amplitudeInit      = 0.3000;
    c.amplitudeBounds    = [0, 1.5000];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

    %% CrNo391
    c = struct();
    c.metab              = 'CrNo391';
    c.componentName      = 'CrNo391';
    c.ppmExpected        = 3.027000;
    c.ppmInit            = 3.027000;
    c.chemShiftHz        = -200.0510;
    c.chemShiftBoundsHz  = [-207.4466, -192.6554];
    c.linewidthInitHz    = 6;
    c.linewidthBoundsHz  = [1, 40];
    c.amplitudeInit      = 0.4000;
    c.amplitudeBounds    = [0, 2.0000];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

    %% MM
    c = struct();
    c.metab              = 'MM';
    c.componentName      = 'MM';
    c.ppmExpected        = 0.916000;
    c.ppmInit            = 0.916000;
    c.chemShiftHz        = -460.2528;
    c.chemShiftBoundsHz  = [-491.0678, -429.4378];
    c.linewidthInitHz    = 30;
    c.linewidthBoundsHz  = [5, 150];
    c.amplitudeInit      = 0.2000;
    c.amplitudeBounds    = [0, 1.0000];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

    %% NAAG
    c = struct();
    c.metab              = 'NAAG';
    c.componentName      = 'NAAG';
    c.ppmExpected        = 2.042000;
    c.ppmInit            = 2.042000;
    c.chemShiftHz        = -321.4621;
    c.chemShiftBoundsHz  = [-328.8577, -314.0665];
    c.linewidthInitHz    = 6;
    c.linewidthBoundsHz  = [1, 40];
    c.amplitudeInit      = 0.1200;
    c.amplitudeBounds    = [0, 0.6000];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

    %% Asp
    c = struct();
    c.metab              = 'Asp';
    c.componentName      = 'Asp';
    c.ppmExpected        = 3.891000;
    c.ppmInit            = 3.891000;
    c.chemShiftHz        = -93.5543;
    c.chemShiftBoundsHz  = [-105.8803, -81.2283];
    c.linewidthInitHz    = 8;
    c.linewidthBoundsHz  = [1, 60];
    c.amplitudeInit      = 0.0600;
    c.amplitudeBounds    = [0, 0.3000];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

    %% Cho
    c = struct();
    c.metab              = 'Cho';
    c.componentName      = 'Cho';
    c.ppmExpected        = 3.185000;
    c.ppmInit            = 3.185000;
    c.chemShiftHz        = -180.5759;
    c.chemShiftBoundsHz  = [-187.9715, -173.1803];
    c.linewidthInitHz    = 6;
    c.linewidthBoundsHz  = [1, 40];
    c.amplitudeInit      = 0.1600;
    c.amplitudeBounds    = [0, 0.8000];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

    %% PCrNo393
    c = struct();
    c.metab              = 'PCrNo393';
    c.componentName      = 'PCrNo393';
    c.ppmExpected        = 3.029000;
    c.ppmInit            = 3.029000;
    c.chemShiftHz        = -199.8045;
    c.chemShiftBoundsHz  = [-207.2001, -192.4089];
    c.linewidthInitHz    = 6;
    c.linewidthBoundsHz  = [1, 40];
    c.amplitudeInit      = 0.2000;
    c.amplitudeBounds    = [0, 1.0000];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

    %% Glc
    c = struct();
    c.metab              = 'Glc';
    c.componentName      = 'Glc';
    c.ppmExpected        = 5.216000;
    c.ppmInit            = 5.216000;
    c.chemShiftHz        = 69.7652;
    c.chemShiftBoundsHz  = [54.9740, 84.5564];
    c.linewidthInitHz    = 8;
    c.linewidthBoundsHz  = [1, 60];
    c.amplitudeInit      = 0.0600;
    c.amplitudeBounds    = [0, 0.3000];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

    %% sI
    c = struct();
    c.metab              = 'sI';
    c.componentName      = 'sI';
    c.ppmExpected        = 3.340000;
    c.ppmInit            = 3.340000;
    c.chemShiftHz        = -161.4706;
    c.chemShiftBoundsHz  = [-168.8662, -154.0750];
    c.linewidthInitHz    = 6;
    c.linewidthBoundsHz  = [1, 40];
    c.amplitudeInit      = 0.0800;
    c.amplitudeBounds    = [0, 0.4000];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

    %% PE
    c = struct();
    c.metab              = 'PE';
    c.componentName      = 'PE';
    c.ppmExpected        = 3.976000;
    c.ppmInit            = 3.976000;
    c.chemShiftHz        = -83.0772;
    c.chemShiftBoundsHz  = [-95.4032, -70.7512];
    c.linewidthInitHz    = 8;
    c.linewidthBoundsHz  = [1, 60];
    c.amplitudeInit      = 0.0600;
    c.amplitudeBounds    = [0, 0.3000];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

    %% Glu
    c = struct();
    c.metab              = 'Glu';
    c.componentName      = 'Glu';
    c.ppmExpected        = 3.743000;
    c.ppmInit            = 3.743000;
    c.chemShiftHz        = -111.7968;
    c.chemShiftBoundsHz  = [-126.5880, -97.0056];
    c.linewidthInitHz    = 8;
    c.linewidthBoundsHz  = [1, 60];
    c.amplitudeInit      = 0.3500;
    c.amplitudeBounds    = [0, 1.7500];
    c.phaseInitDeg       = 0;
    c.phaseBoundsDeg     = [-180, 180];
    components(end+1)    = c;

fprintf('Built %d components\n', numel(components));

%%%%%% REFINE AMPLITUDE INIT FROM SPECTRUM %%%%
%  Estimate local peak amplitude from the actual spectrum for each component.
for i = 1:numel(components)
    ppm0 = components(i).ppmExpected;
    tol  = 0.10;
    mask = ppmAxis >= ppm0-tol & ppmAxis <= ppm0+tol;
    if any(mask)
        localMax = max(specReal(mask));
        if isfinite(localMax) && localMax > 0
            components(i).amplitudeInit = max(localMax / (npts/2), 0.001);
            components(i).amplitudeBounds(2) = max(components(i).amplitudeInit * 5, 0.01);
        end
    end
end

%%%% BUILD PRIOR KNOWLEDGE %%%%
fields.Bounds = {'peakName','chemShift','linewidth','amplitude','phase', ...
                  'chemShiftDelta','amplitudeRatio'};
fields.IV     = {'peakName','chemShift','linewidth','amplitude','phase'};
fields.PK     = {'peakName','multiplet','chemShiftDelta','amplitudeRatio', ...
                  'G_linewidth','G_amplitude','G_phase','RelPhase', ...
                  'G_chemShiftDelta','refPeak'};

nComp = numel(components);
values.boundsCellArray = cell(nComp, 7);
values.IVCellArray     = cell(nComp, 5);
values.PKCellArray     = cell(nComp, 10);

for i = 1:nComp
    c = components(i);
    values.boundsCellArray(i,:) = {c.componentName, c.chemShiftBoundsHz, ...
        c.linewidthBoundsHz, c.amplitudeBounds, c.phaseBoundsDeg, [], []};
    values.IVCellArray(i,:) = {c.componentName, c.chemShiftHz, ...
        c.linewidthInitHz, c.amplitudeInit, c.phaseInitDeg};
    values.PKCellArray(i,:) = {c.componentName, [], [], [], [], [], [], 1, [], 0};
end

pk = AMARES.priorKnowledge.preparePriorKnowledge(fields, values);
pk.notes = sprintf('Generated by basis_set_converter | TE=%.1f ms | SF=%.4f MHz', ...
                   seqte, sf);

%%%%% RUN AMARES %%%%
fprintf('\nRunning OXSA AMARES...\n');
[fitResults, fitStatus, figHandle, CRBResults] = ...
    AMARES.amaresFit(fid, exptParams, pk, showPlot, options);

%%%%%% PRINT RESULTS %%%%
chemShiftHz_fit = fitResults.chemShift(:);
ppm_fit         = carrierPpm + chemShiftHz_fit / sf;
lw_fit          = fitResults.linewidth(:);
amp_fit         = fitResults.amplitude(:) * scaleFactor;
phase_fit       = fitResults.phase(:);

fprintf('\n=== AMARES Results ===\n');
fprintf('%-15s %8s %10s %12s %10s\n', 'Peak', 'ppm', 'LW(Hz)', 'Amplitude', 'Phase');
fprintf('%s\n', repmat('-',1,60));
for i = 1:nComp
    fprintf('%-15s %8.4f %10.3f %12.4g %10.2f\n', ...
        components(i).componentName, ppm_fit(i), lw_fit(i), amp_fit(i), phase_fit(i));
end

%%%%% SAVE RESULTS %%%%
if ~exist(outputDir, 'dir'), mkdir(outputDir); end

componentNames = string({components.componentName}');
resultTable = table(componentNames, ppm_fit, lw_fit, amp_fit, phase_fit, ...
    'VariableNames', {'Component','ppm','linewidthHz','amplitude','phaseDeg'});

save(fullfile(outputDir, 'oxsa_fitResults.mat'), ...
    'fitResults','fitStatus','CRBResults','pk', ...
    'exptParams','components','resultTable','scaleFactor');

writetable(resultTable, fullfile(outputDir, 'oxsa_results.csv'));
fprintf('\nResults saved to: %s\n', outputDir);
