"""
readers/read_profit.py
Basis Set Converter — ProFit reader

Reads a ProFit basis set .mat file generated by make_profit_basis_set_kci.m
into a list of core struct dicts, one per metabolite.

Confirmed structure from profit_struct.mat:
    Top-level variable: basis

    basis.fid  - cell array {1 x nBasis}, each cell is complex (1 x n)
    basis.met  - cell array {1 x nBasis} of metabolite name strings
    basis.bw   - spectral width in Hz
    basis.dt   - dwell time in seconds
    basis.f0   - Larmor frequency in Hz  (= sf * 1e6)
    basis.pts  - number of points
    basis.Bo   - field strength in Tesla

Key notes:
    f0 is stored in Hz — convert to MHz: sf = f0 / 1e6
    fid is a cell array, not a matrix — each cell is one metabolite
    dt = 1/bw (consistent with MARSS convention)

Core struct returned per metabolite:
    {
        'fid'    : np.ndarray, complex, shape (n,)
        'sw'     : float, spectral width in Hz       (= bw)
        'sf'     : float, Larmor frequency in MHz    (= f0 / 1e6)
        'n'      : int, number of points             (= pts)
        'name'   : str, metabolite name
        'Bo'     : float, field strength in Tesla
        'source' : str, path to source file
    }

Entry point:
    read_profit(path) -> list of core struct dicts
"""

import os
import numpy as np
import scipy.io as sio


def _log(*args): pass  # GUI handles display


def read_profit(path):
    """
    Read a ProFit basis set .mat file.

    Parameters
    ----------
    path : str
        Full path to a ProFit .mat file (profit_struct.mat).

    Returns
    -------
    list of core struct dicts, one per metabolite
    """
    path = os.path.abspath(path)

    if not os.path.isfile(path):
        raise RuntimeError(f"File not found: {path}")

    raw = _load_mat(path)

    ############## Find basis struct #############
    basis = _find_basis(raw, path)

    ############## Extract scalar parameters #############
    def _scalar(v):
        return float(np.asarray(v).ravel()[0]) if np.asarray(v).size > 0 else 0.0

    bw  = _scalar(basis.get('bw',  0))
    dt  = _scalar(basis.get('dt',  0))
    f0  = _scalar(basis.get('f0',  0))
    pts = int(_scalar(basis.get('pts', 0)))
    Bo  = _scalar(basis.get('Bo',  0))

    if bw == 0:
        raise RuntimeError(f"Missing or zero bw in {os.path.basename(path)}")
    if f0 == 0:
        raise RuntimeError(f"Missing or zero f0 in {os.path.basename(path)}")

    sf = f0 / 1e6    # Hz → MHz

    ############## Extract cell arrays #############
    fid_raw   = basis.get('fid')
    met_raw   = basis.get('met')
    fid_cells = np.asarray(fid_raw).ravel()
    met_cells = np.asarray(met_raw).ravel()

    if len(fid_cells) != len(met_cells):
        raise RuntimeError(
            f"fid and met cell arrays have different lengths "
            f"({len(fid_cells)} vs {len(met_cells)}) in "
            f"{os.path.basename(path)}"
        )

    n_metabs = len(fid_cells)

    ############## Build one core struct per metabolite #############
    results = []

    for i in range(n_metabs):
        # Extract FID from cell
        fid  = np.asarray(fid_cells[i]).squeeze().astype(complex)
        name = str(np.asarray(met_cells[i]).squeeze()).strip()

        if fid.ndim != 1 or len(fid) == 0:
            _log(f"  WARNING: empty or malformed FID for {name} — skipping")
            continue

        results.append({
            'fid'    : fid,
            'sw'     : bw,
            'sf'     : sf,
            'n'      : len(fid),
            'name'   : name,
            'Bo'     : Bo,
            'source' : path,
        })
        _log(f"  Loaded: {name}")

    if not results:
        raise RuntimeError(
            f"No valid metabolites found in {os.path.basename(path)}"
        )

    _log(f"\n  Total loaded: {len(results)} metabolites")
    _log(f"  sw={bw:.1f} Hz  sf={sf:.4f} MHz  Bo={Bo:.4f} T  n={pts}")
    return results


############## Helpers #############

def _load_mat(path):
    """
    Load .mat file for ProFit.
    Uses squeeze_me=True but NOT simplify_cells — cell arrays must stay as cells.
    """
    try:
        return sio.loadmat(path, squeeze_me=False, struct_as_record=False)
    except NotImplementedError:
        try:
            import mat73
            return mat73.loadmat(path)
        except ImportError:
            raise RuntimeError(
                f"HDF5 v7.3 file — install mat73: pip install mat73"
            )
    except Exception as ex:
        raise RuntimeError(f"Could not load {os.path.basename(path)}: {ex}")


def _find_basis(raw, path):
    """
    Find the basis struct in the loaded .mat file.
    Handles both scipy struct_as_record=False and simplify_cells formats.
    """
    import scipy.io.matlab as _matlab

    # scipy struct_as_record=False returns mat_struct objects
    if 'basis' in raw:
        b = raw['basis']
        # mat_struct case
        if hasattr(b, '_fieldnames'):
            result = {}
            for fn in b._fieldnames:
                result[fn] = getattr(b, fn)
            return result
        # squeeze out extra dims for dict case
        if isinstance(b, dict) and 'fid' in b:
            return b
        # numpy array wrapping a struct
        if hasattr(b, 'dtype') and hasattr(b.dtype, 'names') and b.dtype.names:
            result = {}
            for fn in b.dtype.names:
                result[fn] = b[fn].squeeze() if hasattr(b[fn], 'squeeze') else b[fn]
            return result

    # Top-level variables fallback
    if 'fid' in raw and 'met' in raw and 'bw' in raw:
        return raw

    raise RuntimeError(
        f"Could not find ProFit basis struct in {os.path.basename(path)}."
    )


############## Quick test #############

if __name__ == '__main__':
    import sys

    if len(sys.argv) < 2:
        print("Usage: python read_profit.py <path_to_profit_struct.mat>")
        sys.exit(1)

    results = read_profit(sys.argv[1])
    print(f"\nLoaded {len(results)} metabolites")
    print(f"sw={results[0]['sw']} Hz  sf={results[0]['sf']:.4f} MHz  "
          f"Bo={results[0]['Bo']:.4f} T  n={results[0]['n']}")
    print()
    for r in results:
        print(f"  {r['name']:15s}  |fid[0]|={abs(r['fid'][0]):.4f}  "
              f"|fid[100]|={abs(r['fid'][100]):.4f}")
