"""
writers/write_midas.py
Basis Set Converter — MIDAS Prior XML writer

Writes a MIDAS FITT_Generic_XML prior file from a list of core struct dicts.

Format confirmed from VeSPA Simulation _do_output_midasxml():

    <FITT_Generic_XML Creation_date="..." Creation_time="...">
      <VESPA_SIMULATION_MIDAS_EXPORT>
        <comment line="line0000" value="..."/>
        ...
      </VESPA_SIMULATION_MIDAS_EXPORT>
      <PRIOR_METABOLITE_INFORMATION>
        <param name="fitt_PriorLine00001"
               value="NAA++0++0++0++0++2.008++1.0++0.0"/>
        ...
      </PRIOR_METABOLITE_INFORMATION>
    </FITT_Generic_XML>

Each param value is '++'-joined:
    abbr ++ dim1 ++ dim2 ++ dim3 ++ line_index ++ ppm ++ area ++ phase

Dims are always 0 for a single-loop export (no TE or loop variation).
PPM positions from metabList.mat literature shifts (same as write_vespa.py).
Areas from FFT spectrum at those positions, normalized to dominant=1.0.

Entry point:
    write_midas(basis_list, outpath, seqte, metablist_path) → .xml file
"""

import os
import numpy as np
from datetime import datetime
import xml.etree.ElementTree as ET
from xml.dom import minidom


PPM_CALIB = 4.65

# Import shared helpers from write_vespa
def _get_peaks(basis_list, ppm_table):
    """Shared peak detection logic — import from write_vespa."""
    from writers.write_vespa import _get_lit_ppms, _peaks_at_ppms, PPM_CALIB as VC
    results = {}
    for core in basis_list:
        name      = core.get('name', 'unknown')
        fid       = np.asarray(core['fid']).ravel()
        sf        = float(core.get('sf') or 123.26)
        sw        = float(core.get('sw') or 4000.0)
        ppm_calib = float(core.get('ppmCalib') or VC)
        lit_lines = _get_lit_ppms(name, ppm_table)
        peaks     = _peaks_at_ppms(fid, sf, sw, lit_lines, ppm_calib=ppm_calib)
        if peaks:
            max_area = max(abs(a) for _, a, _ in peaks)
            if max_area > 0:
                peaks = [(p, round(a/max_area, 12), ph) for p, a, ph in peaks]
            peaks = [(p, a, ph) for p, a, ph in peaks if a > 0]
        results[name] = peaks
    return results


def write_midas(basis_list, outpath,
                seqte=26.0,
                metablist_path=None):
    """
    Write a MIDAS FITT_Generic_XML prior XML file.

    Parameters
    ----------
    basis_list     : list of core struct dicts
    outpath        : str, full path for output .xml file
    seqte          : float, echo time in ms
    metablist_path : str or None, path to metabList.mat
    """
    outpath = os.path.abspath(outpath)
    os.makedirs(os.path.dirname(outpath) or '.', exist_ok=True)

    if not basis_list:
        raise RuntimeError("basis_list is empty")

    # Load ppm table
    from writers.write_vespa import _load_metablist, METAB_PPM_TABLE
    ppm_table = _load_metablist(metablist_path) if metablist_path \
                else {k: [(p, 1) for p in v] for k, v in METAB_PPM_TABLE.items()}

    # Get peaks for all metabolites
    all_peaks = _get_peaks(basis_list, ppm_table)

    now = datetime.now()
    stamp_date = now.strftime('%Y-%m-%d')
    stamp_time = now.strftime('%H:%M:%S')

    ################ Build XML ################
    root = ET.Element('FITT_Generic_XML', {
        'Creation_date': stamp_date,
        'Creation_time': stamp_time,
    })

    # Comment node
    comment_elem = ET.SubElement(root, 'VESPA_SIMULATION_MIDAS_EXPORT')
    comments = [
        'MIDAS Prior XML generated by basis_set_converter',
        f'Source: {basis_list[0].get("source", "unknown")}',
        f'TE: {seqte} ms',
        f'Metabolites: {len(basis_list)}',
        'https://github.com/SAIL-GuoLab/basis_set_converter',
    ]
    for i, line in enumerate(comments):
        ET.SubElement(comment_elem, 'comment', {
            'line' : f'line{i:04d}',
            'value': line,
        })

    # Prior metabolite information
    prior_elem = ET.SubElement(root, 'PRIOR_METABOLITE_INFORMATION')

    irun = 1
    for core in basis_list:
        name  = core.get('name', 'unknown')
        peaks = all_peaks.get(name, [])

        if not peaks:
            print(f"  WARNING: no peaks for {name} — skipping")
            continue

        for line_idx, (ppm, area, phase) in enumerate(peaks):
            pname = f'fitt_PriorLine{irun:05d}'
            # value: abbr++dim1++dim2++dim3++line_index++ppm++area++phase
            value = '++'.join([
                name,
                '0', '0', '0',          # dims always 0
                str(line_idx),
                str(round(ppm,   6)),
                str(round(area,  12)),
                str(round(phase, 6)),
            ])
            ET.SubElement(prior_elem, 'param', {
                'name' : pname,
                'value': value,
            })
            irun += 1

        print(f"  {name:15s}  {len(peaks):2d} peaks  "
              f"dominant={peaks[0][0]:.4f} ppm")

    # Write pretty XML
    xml_str = minidom.parseString(
        ET.tostring(root, encoding='utf-8')
    ).toprettyxml(indent='  ', encoding='utf-8')

    with open(outpath, 'wb') as f:
        f.write(xml_str)

    print(f"\n  Done. MIDAS prior XML: {os.path.basename(outpath)}")
    print(f"  {len(basis_list)} metabolites  TE={seqte} ms")


################# Command line ################

if __name__ == '__main__':
    import sys
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    if len(sys.argv) < 3:
        print("Usage: python write_midas.py <input_folder> <output.xml> [te_ms] [metabList.mat]")
        sys.exit(1)

    from readers.read_marss import read_marss_file, read_marss_folder
    input_path     = sys.argv[1]
    outpath        = sys.argv[2]
    seqte          = float(sys.argv[3]) if len(sys.argv) > 3 else 26.0
    metablist_path = sys.argv[4] if len(sys.argv) > 4 else None

    basis_list = read_marss_folder(input_path) if os.path.isdir(input_path) \
                 else [read_marss_file(input_path)]
    print(f"Loaded {len(basis_list)} metabolites\n")
    write_midas(basis_list, outpath, seqte=seqte, metablist_path=metablist_path)
