"""
writers/write_gava.py
Basis Set Converter — GAVA Text writer

Writes a GAVA text prior file from a list of core struct dicts.

Format confirmed from VeSPA Simulation _do_output_gava():

    ;comment lines starting with semicolons
    ;...
    abbr \\t dim1 \\t dim2 \\t dim3 \\t line_index \\t ppm \\t area \\t phase

Where:
    abbr       = metabolite name/abbreviation
    dim1/2/3   = loop dimension values (0 for single export)
    line_index = index of this peak within the metabolite
    ppm        = peak chemical shift
    area       = relative peak area
    phase      = peak phase in degrees

PPM positions from metabList.mat literature shifts.
Areas from FFT spectrum, normalized to dominant=1.0 per metabolite.

Entry point:
    write_gava(basis_list, outpath, seqte, metablist_path) -> .txt file
"""

import os
import numpy as np
from datetime import datetime


def write_gava(basis_list, outpath,
               seqte=26.0,
               metablist_path=None):
    """
    Write a GAVA text prior file.

    Parameters
    ----------
    basis_list     : list of core struct dicts
    outpath        : str, full path for output .txt file
    seqte          : float, echo time in ms
    metablist_path : str or None, path to metabList.mat
    """
    outpath = os.path.abspath(outpath)
    os.makedirs(os.path.dirname(outpath) or '.', exist_ok=True)

    if not basis_list:
        raise RuntimeError("basis_list is empty")

    # Load ppm table
    from writers.write_vespa import (_load_metablist, _get_lit_ppms,
                                     _peaks_at_ppms, METAB_PPM_TABLE,
                                     PPM_CALIB)
    ppm_table = _load_metablist(metablist_path) if metablist_path \
                else {k: [(p, 1) for p in v] for k, v in METAB_PPM_TABLE.items()}

    now = datetime.now().strftime('%Y-%m-%dT%H:%M:%S')

    lines = []

    # Comment header — GAVA comment lines start with ';'
    comments = [
        'GAVA Text Prior generated by basis_set_converter',
        f'Created: {now}',
        f'Source: {basis_list[0].get("source", "unknown")}',
        f'TE: {seqte} ms',
        f'Metabolites: {len(basis_list)}',
        '',
        'Simulation Spectral Results',
        '-' * 75,
    ]
    for c in comments:
        lines.append(f';{c}')

    # Data lines
    for core in basis_list:
        name      = core.get('name', 'unknown')
        fid       = np.asarray(core['fid']).ravel()
        sf        = float(core.get('sf') or 123.26)
        sw        = float(core.get('sw') or 4000.0)
        ppm_calib = float(core.get('ppmCalib') or PPM_CALIB)

        lit_lines = _get_lit_ppms(name, ppm_table)
        peaks     = _peaks_at_ppms(fid, sf, sw, lit_lines, ppm_calib=ppm_calib)

        if not peaks:
            print(f"  WARNING: no peaks for {name} — skipping")
            continue

        # Normalize: dominant = 1.0
        max_area = max(abs(a) for _, a, _ in peaks)
        if max_area > 0:
            peaks = [(p, round(a/max_area, 12), ph) for p, a, ph in peaks]
        peaks = [(p, a, ph) for p, a, ph in peaks if a > 0]

        for line_idx, (ppm, area, phase) in enumerate(peaks):
            # Format: abbr \t dim1 \t dim2 \t dim3 \t idx \t ppm \t area \t phase
            row = '\t'.join([
                name,
                '0', '0', '0',
                str(line_idx),
                str(round(ppm,   6)),
                str(round(area,  12)),
                str(round(phase, 6)),
            ])
            lines.append(row)

        print(f"  {name:15s}  {len(peaks):2d} peaks  "
              f"dominant={peaks[0][0]:.4f} ppm")

    # Write file
    with open(outpath, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')

    print(f"\n  Done. GAVA text: {os.path.basename(outpath)}")
    print(f"  {len(basis_list)} metabolites  TE={seqte} ms")


######################## Command line #######################

if __name__ == '__main__':
    import sys
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    if len(sys.argv) < 3:
        print("Usage: python write_gava.py <input_folder> <output.txt> [te_ms] [metabList.mat]")
        sys.exit(1)

    from readers.read_marss import read_marss_file, read_marss_folder
    input_path     = sys.argv[1]
    outpath        = sys.argv[2]
    seqte          = float(sys.argv[3]) if len(sys.argv) > 3 else 26.0
    metablist_path = sys.argv[4] if len(sys.argv) > 4 else None

    basis_list = read_marss_folder(input_path) if os.path.isdir(input_path) \
                 else [read_marss_file(input_path)]
    print(f"Loaded {len(basis_list)} metabolites\n")
    write_gava(basis_list, outpath, seqte=seqte, metablist_path=metablist_path)
